services:
  comfyui:
    build:
      context: .
    image: localhost/comfyui:latest
    restart: unless-stopped
    container_name: comfyui
    ports:
      - "${ENDPOINT:-127.0.0.1:8188}:8188"
    volumes:
      - ${DATA:-./data}/models:/app/models
      - ${DATA:-./data}/input:/app/input
      - ${DATA:-./data}/output:/app/output
      - ${DATA:-./data}/user:/app/user
      - ${DATA:-./data}/custom_nodes:/app/custom_nodes
      - ${DATA:-./data}/triton-cache:/root/.triton
    devices:
      - nvidia.com/gpu=all
